language: bash

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker-ce

install:
  - docker pull sickcodes/docker-osx:latest

before_script:
  - export DISPLAY=:99.0
  - export QEMU_AUDIO_DRV=pa
  - export QEMU_PA_SAMPLES=128
  - export QEMU_PA_SERVER=127.0.0.1
  - export QEMU_PA_CLIENT_NAME="QEMU"
  - export QEMU_PA_STREAM_NAME="QEMU"

script:
  - docker run --privileged -e "DISPLAY=${DISPLAY}" -v /tmp/.X11-unix:/tmp/.X11-unix sickcodes/docker-osx:latest
