language: bash

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker-ce
  - sudo apt-get install -y qemu-system-x86 qemu-utils

install:
  - docker pull sickcodes/docker-osx:latest

before_script:
  - export DISPLAY=:99.0

script:
  - sudo modprobe kvm
  - echo "yokogawa" 
